version: '3.8'

services:
  core-db:
    container_name: mysql_core_db_dev
    build:
      context: .
      dockerfile: ./docker/dev/image/mysql/Dockerfile
      args:
        mysql_root_user: ${MYSQL_ROOT_USER}
        mysql_root_password: ${MYSQL_ROOT_PASSWORD}
        mysql_database: ${MYSQL_DATABASE}
        mysql_user: ${MYSQL_USER}
        mysql_password: ${MYSQL_PASSWORD}
        mysql_port: ${MYSQL_PORT}
        mysql_conn: ${MYSQL_CONN}
    restart: unless-stopped
    volumes:
      - core_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          '${MYSQL_HOST}',
          '-u',
          '${MYSQL_USER}',
          '--password=${MYSQL_PASSWORD}',
        ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s

  core_db_admin:
    container_name: phpmyadmin_core_db_debug
    build:
      context: .
      dockerfile: ./docker/debug/image/phpmyadmin/Dockerfile
      args:
        mysql_root_password: ${MYSQL_ROOT_PASSWORD}
        phpmyadmin_port: ${PHPMYADMIN_PORT}
        phpmyadmin_pma_host: core-db
        phpmyadmin_pma_port: 3306
        phpmyadmin_pma_arbitrary: 0
    restart: unless-stopped
    depends_on:
      core-db:
        condition: service_healthy
    ports:
      - '127.0.0.1:${PHPMYADMIN_PORT}:80'

  cache-db:
    container_name: redis_cache_db_dev
    build:
      context: .
      dockerfile: ./docker/dev/image/redis/Dockerfile
      args:
        redis_server_pass: ${REDIS_SERVER_PASS}
        redis_client_user: ${REDIS_CLIENT_USER}
        redis_client_pass: ${REDIS_CLIENT_PASS}
        redis_port: ${REDIS_PORT}
        redis_host: ${REDIS_HOST}
        redis_conn: ${REDIS_CONN}
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - cache_data:/data

  cache_db_commander:
    container_name: redis-commander_cache_db_dev
    build:
      context: .
      dockerfile: ./docker/dev/image/redis-commander/Dockerfile
      args:
        port: 8081
        redis_client_pass: ${REDIS_SERVER_PASS}
        redis_client_port: 6379
        redis_client_host: cache-db
        redis_client_db_index: ${REDIS_DB}
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      cache-db:
        condition: service_healthy

volumes:
  core_data:
  cache_data:
