#!/bin/bash

set -e

master_loaded=0

while [ $master_loaded -lt 1 ]
do
    if ! mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e 'select 1;' | grep -q 1; then
        sleep 1
    else
        master_loaded=1
    fi
done

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "FLUSH TABLES WITH READ LOCK;"
LOG_FILE=$(mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e 'SHOW MASTER STATUS\G' | awk '/File/ {print $2}')
LOG_POS=$(mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e 'SHOW MASTER STATUS\G' | awk '/Position/ {print $2}')
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "UNLOCK TABLES;"

mysql -u ${MYSQL_ROOT_USER} --password="${MYSQL_ROOT_PASSWORD}" ${MYSQL_DATABASE} -e "CHANGE MASTER TO MASTER_HOST='${MYSQL_MASTER_DATABASE_HOST}', MASTER_USER='${MYSQL_MASTER_REPLICATION_USER}', MASTER_PASSWORD='${MYSQL_MASTER_REPLICATION_PASSWORD}', MASTER_LOG_FILE='$LOG_FILE', MASTER_LOG_POS=$LOG_POS, MASTER_SSL=0;;"

mysql -u ${MYSQL_ROOT_USER} --password="${MYSQL_ROOT_PASSWORD}" ${MYSQL_DATABASE} -e "START SLAVE;"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE DATABASE IF NOT EXISTS clients_schema;"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE DATABASE IF NOT EXISTS short_urls_schema;"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE DATABASE IF NOT EXISTS locks_schema;"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE SCHEMA IF NOT EXISTS clients_schema CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE SCHEMA IF NOT EXISTS short_urls_schema CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE SCHEMA IF NOT EXISTS locks_schema CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE TABLE IF NOT EXISTS locks_schema.locks (name ENUM('SHORT_URL_COUNTER') UNIQUE NOT NULL);"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE TABLE IF NOT EXISTS clients_schema.plans (id VARCHAR(36), create_recharge_time INT NOT NULL, delete_recharge_time INT NOT NULL, tier ENUM('FREE') UNIQUE NOT NULL);"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "ALTER TABLE clients_schema.plans ADD CONSTRAINT pk_plans_id PRIMARY KEY (id);"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE UNIQUE INDEX idx_btree_plans_by_id ON clients_schema.plans (id);"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE UNIQUE INDEX idx_btree_plans_by_tier ON clients_schema.plans (tier);"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "INSERT INTO clients_schema.plans (id, create_recharge_time, delete_recharge_time, tier) VALUES ('5532b773-be2f-42e5-a4da-a0856bf0d62c', 3600000, 3600000, 'FREE');"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE TABLE IF NOT EXISTS clients_schema.clients (id VARCHAR(36), email VARCHAR(320) UNIQUE NOT NULL, password TEXT NOT NULL, full_name VARCHAR(255) NOT NULL, plan_id VARCHAR(36) NOT NULL);"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "ALTER TABLE clients_schema.clients ADD CONSTRAINT pk_clients_id PRIMARY KEY (id);"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "ALTER TABLE clients_schema.clients ADD CONSTRAINT fk_clients_plan_id FOREIGN KEY (plan_id) REFERENCES clients_schema.plans (id) ON UPDATE CASCADE;"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE UNIQUE INDEX idx_btree_clients_by_email ON clients_schema.clients(email);"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE UNIQUE INDEX idx_btree_clients_by_id ON clients_schema.clients(id);"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE TABLE IF NOT EXISTS clients_schema.quota (client_id VARCHAR(36), plan_id VARCHAR(36) NOT NULL, quota_remaining_creation_links INT NOT NULL, quota_remaining_deletion_links INT NOT NULL, plan_create_recharge_time_refreshes_in BIGINT NOT NULL, plan_delete_recharge_time_refreshes_in BIGINT NOT NULL);"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "ALTER TABLE clients_schema.quota ADD CONSTRAINT pk_quota_client_id PRIMARY KEY (client_id);"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "ALTER TABLE clients_schema.quota ADD CONSTRAINT fk_quota_client_id FOREIGN KEY (client_id) REFERENCES clients_schema.clients (id) ON DELETE CASCADE ON UPDATE CASCADE;"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "ALTER TABLE clients_schema.quota ADD CONSTRAINT fk_quota_plan_id FOREIGN KEY (plan_id) REFERENCES clients_schema.plans (id) ON UPDATE CASCADE;"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE UNIQUE INDEX idx_btree_quota_by_client_id_plan_id ON clients_schema.quota (plan_id, client_id);"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE TABLE IF NOT EXISTS short_urls_schema.counter (table_name VARCHAR(255), last_id TINYTEXT NOT NULL);"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "ALTER TABLE short_urls_schema.counter ADD CONSTRAINT pk_counter_client_id PRIMARY KEY (table_name);"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE UNIQUE INDEX idx_btree_counter_by_table_name ON short_urls_schema.counter (table_name);"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "INSERT INTO short_urls_schema.counter (table_name, last_id) VALUES ('short_urls', '0000000000');"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE TABLE IF NOT EXISTS short_urls_schema.short_urls (id VARCHAR(10), client_id VARCHAR(36) NOT NULL, long_url TEXT NOT NULL, created_at BIGINT NOT NULL, deleted_at BIGINT DEFAULT NULL, is_deleted BOOLEAN NOT NULL DEFAULT false);"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "ALTER TABLE short_urls_schema.short_urls ADD CONSTRAINT pk_short_urls_id PRIMARY KEY (id);"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "ALTER TABLE short_urls_schema.short_urls ADD CONSTRAINT fk_short_urls_client_id FOREIGN KEY (client_id) REFERENCES clients_schema.clients (id) ON UPDATE CASCADE ON DELETE CASCADE;"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "CREATE UNIQUE INDEX idx_btree_short_urls_by_id ON short_urls_schema.short_urls (id);"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "GRANT SELECT ON clients_schema.plans TO '${MYSQL_USER}'@'%';"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "GRANT SELECT, INSERT, UPDATE ON clients_schema.clients TO '${MYSQL_USER}'@'%';"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "GRANT SELECT, INSERT, UPDATE ON clients_schema.quota TO '${MYSQL_USER}'@'%';"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "GRANT SELECT, INSERT, UPDATE ON short_urls_schema.short_urls TO '${MYSQL_USER}'@'%';"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "GRANT SELECT, UPDATE ON short_urls_schema.counter TO '${MYSQL_USER}'@'%';"
mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "GRANT SELECT, INSERT, DELETE ON locks_schema.locks TO '${MYSQL_USER}'@'%';"
# mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "GRANT LOCK TABLES ON short_urls_schema.* TO '${MYSQL_USER}'@'%';"

mysql -h ${MYSQL_MASTER_DATABASE_HOST} -u ${MYSQL_MASTER_DATABASE_USER} --password="${MYSQL_MASTER_DATABASE_PASSWORD}" ${MYSQL_MASTER_DATABASE} -e "FLUSH PRIVILEGES;"
