@url = http://localhost:3000

# @name createAccount
POST {{url}}/clients/create-account
content-type: application/json

{
    "email": "test@mail.com",
    "password": "12345678bB#",
    "fullName": "Gabriel Ferrari Tarallo Ferraz"
}

###

# @name loginToAccount
POST {{url}}/clients/login
content-type: application/json

{
    "email": "test@mail.com",
    "password": "12345678bB#"
}

###

@accessToken = {{loginToAccount.response.body.accessToken}}

# @name createShortUrl
POST {{url}}
Content-Type: application/json
Authorization: {{accessToken}}

{
    "longUrl": "https://www.google.com"
}

###

@shortLink = {{createShortUrl.response.body.id}}

# @name redirect
GET {{url}}/{{shortLink}}
Content-Type: application/json

###

# @name deleteUrl
DELETE {{url}}/{{shortLink}}
Content-Type: application/json
Authorization: {{accessToken}}
