#!/bin/bash

set -e

mysql -u ${MYSQL_ROOT_USER} --password="${MYSQL_ROOT_PASSWORD}" ${MYSQL_DATABASE} -e "CREATE USER '${MYSQL_REPLICATION_USER}'@'%' IDENTIFIED WITH 'mysql_native_password' BY '${MYSQL_REPLICATION_PASSWORD}';"

mysql -u ${MYSQL_ROOT_USER} --password="${MYSQL_ROOT_PASSWORD}" ${MYSQL_DATABASE} -e "GRANT REPLICATION SLAVE ON *.* TO '${MYSQL_REPLICATION_USER}'@'%';"

mysql -u ${MYSQL_ROOT_USER} --password="${MYSQL_ROOT_PASSWORD}" ${MYSQL_DATABASE} -e "FLUSH PRIVILEGES;"
